# Generated by Django 2.1.5 on 2019-01-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_category',
        ),
    ]
