# Generated by Django 2.1.5 on 2019-01-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_blogpost_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='parent_id',
            field=models.ManyToManyField(blank=True, related_name='_postcategory_parent_id_+', to='rest.PostCategory'),
        ),
    ]
