# Generated by Django 2.1.5 on 2019-01-29 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_postcategory_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.PostCategory'),
        ),
    ]
