# Generated by Django 2.1.5 on 2019-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_blogpost_post_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_content', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_privacy',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=50, null=True),
        ),
    ]
