# Generated by Django 2.1.5 on 2019-02-05 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0008_auto_20190205_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='token_clientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='token_expired',
            field=models.DateTimeField(null=True),
        ),
    ]
